package jp.co.cyberagent.android.gpuimage;


/**
 * 滤镜类型
 * @author sulei
 */
public enum GPUFilterType 
{
	FILTER_NONE, // 无滤镜
	FILTER_MAGIC_FAIRYTALE, // 童话
	FILTER_MAGIC_SUNRISE, // 日出
	FILTER_MAGIC_SUNSET, // 日落
	FILTER_MAGIC_WHITECAT, // 白猫
	FILTER_MAGIC_BLACKCAT, // 黑猫
	FILTER_MAGIC_BEAUTY, // 美肤
	FILTER_MAGIC_SKINWHITEN, // 美白,与MagicBilateralFilter滤镜同时使用,效果更好,不过性能消耗较大
	FILTER_MAGIC_SWEETS, // 甜品
	FILTER_MAGIC_ROMANCE, // 浪漫
	FILTER_MAGIC_SAKURA, // 樱花
	FILTER_MAGIC_WARM, // 温暖
	FILTER_MAGIC_ANTIQUE, // 复古
	FILTER_MAGIC_CALM, // 平静
	FILTER_MAGIC_LATTE, // 拿铁
	FILTER_MAGIC_COOL, // 冰冷
	FILTER_MAGIC_EMERALD, // 祖母绿
	FILTER_MAGIC_EVERGREEN, // 常青
	FILTER_MAGIC_AMARO, // Amaro
	FILTER_MAGIC_BRANNAN, // Brannan
	FILTER_MAGIC_BROOKLYN, // Brooklyn
	FILTER_MAGIC_EARLYBIRD, // EarlyBird 晨起
	FILTER_MAGIC_FREUD, // Freud
	FILTER_MAGIC_HEFE,  // Hefe
	FILTER_MAGIC_HUDSON, // Hudson
	FILTER_MAGIC_INKWELL, // Inkwell 黑白
	FILTER_MAGIC_KEVIN, // Kevin
	FILTER_MAGIC_LOMO, // Lomo
	FILTER_MAGIC_N1977, // 1977复古
	FILTER_MAGIC_NASHVILLE, // Nashville
	FILTER_MAGIC_PIXAR, // Pixar
	FILTER_MAGIC_RISE, // Rise 日出
	FILTER_MAGIC_SIERRA, // Sierra
	FILTER_MAGIC_SUTRO, // Sutro
	FILTER_MAGIC_TOASTER, // Toaster
	FILTER_MAGIC_WALDEN, // Walden
	FILTER_GPUIMAGE_SKETCH, // 素描
	FILTER_GPUIMAGE_COLORINVERT, // 反色
	FILTER_GPUIMAGE_VIGNETTE, // 四周暗色
	FILTER_GPUIMAGE_TONECURVE, // 亮白，有类似美白效果
	FILTER_GPUIMAGE_GLASSSPHERE, // 透过玻璃球效果，类似猫眼、鱼眼效果
	FILTER_GPUIMAGE_LAPLACIAN, // 拉普拉斯矩阵，类似雕塑效果
	FILTER_GPUIMAGE_SWIRL, // 漩涡扭曲效果
	FILTER_GPUIMAGE_THIN_FACE, // 漩涡扭曲效果
	FILTER_GPUIMAGE_MASK
}
